import type {
  Deck,
  PresentationQualityIssue,
  PresentationReview,
  SlideNarration,
} from "@slidespeech/types";

import { evaluateDeckQuality } from "./evaluation";
import {
  ensureDeckTheme,
  ensureNarrationSegments,
  reviewIssueCodeRequiresNarrationRepair,
  type ValidationIssue,
} from "./session-deck-quality";
import { nowIso } from "./utils";

export const countReadySlides = (
  deck: Deck,
  narrationBySlideId: Record<string, SlideNarration>,
): number =>
  deck.slides.reduce(
    (count, slide) => count + (narrationBySlideId[slide.id] ? 1 : 0),
    0,
  );

export const buildGenerationStatus = (
  deck: Deck,
  narrationReadySlides: number,
  backgroundEnrichmentPending: boolean,
  lastCompletedAt?: string,
): NonNullable<Deck["metadata"]["generation"]> => ({
  narrationReadySlides,
  totalSlides: deck.slides.length,
  backgroundEnrichmentPending,
  ...(lastCompletedAt ? { lastCompletedAt } : {}),
});

const dedupeValidationIssues = (
  issues: ValidationIssue[],
): ValidationIssue[] => {
  const seen = new Set<string>();
  const deduped: ValidationIssue[] = [];

  for (const issue of issues) {
    const key = `${issue.code}:${issue.slideId ?? ""}:${issue.message}`;
    if (seen.has(key)) {
      continue;
    }

    seen.add(key);
    deduped.push(issue);
  }

  return deduped;
};

export const mergeValidationMetadata = (
  deck: Deck,
  additionalIssues: ValidationIssue[],
  summary?: string,
  overallScore?: number,
): NonNullable<Deck["metadata"]["validation"]> => {
  const combinedIssues = dedupeValidationIssues([
    ...(deck.metadata.validation?.issues ?? []),
    ...additionalIssues,
  ]);

  return {
    passed: !combinedIssues.some((issue) => issue.severity === "error"),
    repaired: Boolean(deck.metadata.validation?.repaired),
    validatedAt: nowIso(),
    ...((summary ?? deck.metadata.validation?.summary) !== undefined
      ? { summary: summary ?? deck.metadata.validation?.summary }
      : {}),
    ...((overallScore ?? deck.metadata.validation?.overallScore) !== undefined
      ? {
          overallScore:
            overallScore ?? deck.metadata.validation?.overallScore,
        }
      : {}),
    issues: combinedIssues,
  };
};

export const buildLocalBaselinePresentationReview = (
  validationIssues: ValidationIssue[],
  note?: string,
): PresentationReview => {
  const issues: PresentationQualityIssue[] = validationIssues.map((issue) => ({
    code: issue.code,
    severity: issue.severity,
    dimension:
      issue.code.includes("narration")
        ? "narration"
        : issue.code.includes("visual")
          ? "visual"
          : issue.code.includes("ground")
            ? "grounding"
            : "coherence",
    message: issue.message,
    ...(issue.slideId ? { slideId: issue.slideId } : {}),
  }));

  const hasError = issues.some((issue) => issue.severity === "error");
  const scorePenalty = issues.reduce((sum, issue) => {
    switch (issue.severity) {
      case "error":
        return sum + 0.18;
      case "warning":
        return sum + 0.06;
      case "info":
      default:
        return sum + 0.02;
    }
  }, 0);

  return {
    approved: !hasError,
    overallScore: Math.max(0.55, Number((0.92 - scorePenalty).toFixed(2))),
    summary:
      note ??
      "Local presentation quality baseline used because the LLM review step was unavailable.",
    issues,
    repairedNarrations: [],
  };
};

export const mergeNewNarrationsPreservingExisting = (
  existingBySlideId: Record<string, SlideNarration>,
  candidateNarrations: SlideNarration[],
): Record<string, SlideNarration> => {
  const candidateBySlideId = Object.fromEntries(
    candidateNarrations.map((narration) => [
      narration.slideId,
      ensureNarrationSegments(narration),
    ]),
  );

  return {
    ...candidateBySlideId,
    ...existingBySlideId,
  };
};

const resolveSlideIdFromReviewIssue = (
  deck: Deck,
  issue: PresentationReview["issues"][number],
): string | null => {
  if (issue.slideId && deck.slides.some((slide) => slide.id === issue.slideId)) {
    return issue.slideId;
  }

  return null;
};

export const collectNarrationRevisionIssuesFromReview = (
  deck: Deck,
  review: PresentationReview,
): ValidationIssue[] =>
  review.issues
    .filter((reviewIssue) => reviewIssueCodeRequiresNarrationRepair(reviewIssue.code))
    .map((reviewIssue) => {
      const slideId = resolveSlideIdFromReviewIssue(deck, reviewIssue);
      const slide = slideId
        ? deck.slides.find((candidate) => candidate.id === slideId)
        : undefined;

      return {
        code: "narration_revision_required",
        message: `Narration for "${slide?.title ?? slideId ?? "an unknown slide"}" was rejected by review and must be regenerated by the narration stage.`,
        severity: "error" as const,
        ...(slideId ? { slideId } : {}),
      };
    });

export const finalizeDeckMetadata = (
  deck: Deck,
  narrations: SlideNarration[],
  review: PresentationReview,
  additionalValidationIssues: ValidationIssue[] = [],
): Deck => {
  const reviewIssues: ValidationIssue[] = review.issues.map((issue) => ({
    code: issue.code,
    message: issue.message,
    severity: issue.severity,
    ...(issue.slideId ? { slideId: issue.slideId } : {}),
  }));
  const validation = mergeValidationMetadata(
    deck,
    [...additionalValidationIssues, ...reviewIssues],
    review.summary,
    review.overallScore,
  );
  const deckWithValidation: Deck = {
    ...deck,
    metadata: {
      ...deck.metadata,
      validation: {
        ...validation,
        passed: validation.passed && review.approved,
      },
    },
  };
  const evaluation = evaluateDeckQuality(deckWithValidation, narrations);

  return ensureDeckTheme({
    ...deckWithValidation,
    updatedAt: nowIso(),
    metadata: {
      ...deckWithValidation.metadata,
      evaluation,
      generation: buildGenerationStatus(
        deck,
        narrations.length,
        false,
        nowIso(),
      ),
    },
  });
};
